baseURL = 'https://polarisccc.github.io/newssite/'
canonifyurls = true
languageCode = 'zh'
title = '雪域印象'
publishDir="docs"
theme = 'ananke'
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true



